# Generated by Django 5.1 on 2024-09-27 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('objectid', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('c_reg', models.FloatField()),
                ('nom_reg', models.CharField(max_length=255)),
                ('c_com', models.CharField(max_length=10)),
                ('nom_com', models.CharField(max_length=255)),
                ('c_ant', models.CharField(max_length=10)),
                ('c_vig', models.FloatField()),
                ('c_mad', models.CharField(max_length=10)),
                ('c_nmad', models.CharField(max_length=10)),
                ('c_depend', models.FloatField()),
                ('depen', models.CharField(max_length=255)),
                ('perenec', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('ambito', models.CharField(max_length=255)),
                ('urgencia', models.CharField(max_length=3)),
                ('certifica', models.CharField(max_length=3)),
                ('depen_a', models.CharField(max_length=255)),
                ('nivel', models.CharField(max_length=255)),
                ('via', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=255)),
                ('fono', models.CharField(blank=True, max_length=255, null=True)),
                ('f_inicio', models.FloatField()),
                ('f_reaper', models.CharField(max_length=255)),
                ('sapu', models.CharField(max_length=255)),
                ('f_cambio', models.CharField(max_length=255)),
                ('tipo_camb', models.CharField(max_length=255)),
                ('prestador', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('nivel_com', models.CharField(max_length=255)),
                ('modalidad', models.CharField(max_length=255)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
            options={
                'verbose_name': 'consultorio',
                'verbose_name_plural': 'consultorios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.DateField()),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'ordering': ['usuario', 'ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='consultorio.consultorio')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='consultorio.paciente')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['fecha_reserva'],
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('medicacion', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('gravedad', models.CharField(max_length=255)),
                ('modalidad', models.CharField(max_length=255)),
                ('rut_profesional', models.CharField(max_length=12)),
                ('id_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=255)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to='consultorio.usuario')),
            ],
            options={
                'verbose_name': 'profesional',
                'verbose_name_plural': 'profesionales',
                'ordering': ['usuario', 'especialidad'],
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='consultorio.usuario'),
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to='consultorio.usuario')),
            ],
            options={
                'verbose_name': 'administrador',
                'verbose_name_plural': 'administradores',
                'ordering': ['usuario'],
            },
        ),
    ]
