# Generated by Django 5.0.6 on 2024-07-07 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultorio',
            old_name='object_id',
            new_name='objectid',
        ),
    ]
