# Generated by Django 5.1 on 2024-09-27 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0002_rename_object_id_consultorio_objectid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=255)),
                ('fecha_reserva', models.DateTimeField()),
                ('motivo', models.TextField()),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='consultorio.consultorio')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['fecha_reserva'],
            },
        ),
    ]
