# Generated by Django 5.1 on 2024-12-13 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0002_remove_reserva_consultorio_remove_reserva_paciente_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
    ]
