# Generated by Django 5.1 on 2024-12-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0003_delete_administrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='c_com',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='c_reg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
