# Generated by Django 5.0.6 on 2024-07-07 18:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_profile_email_alter_profile_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Paciente',
        ),
    ]
