# Generated by Django 5.0.6 on 2024-07-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_rename_profile_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='user',
            new_name='username',
        ),
    ]
