# Generated by Django 5.0.6 on 2024-07-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_rename_user_paciente_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='username',
            new_name='rut',
        ),
    ]
