# Generated by Django 5.0.6 on 2024-07-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_rename_username_paciente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
