# Generated by Django 5.0.6 on 2024-07-07 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_alter_paciente_rut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=12, null=True)),
                ('numero_region', models.IntegerField(blank=True, null=True)),
                ('rut', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Paciente',
        ),
    ]
