# Generated by Django 5.0.6 on 2024-07-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_rename_rut_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
