# Generated by Django 5.0.6 on 2024-07-07 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_rename_username_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
